import type { Product, Video, Category, Review } from '@/types';

export const AFFILIATE_TAG = process.env.AFFILIATE_TAG || 'gadgetlens-21';

export function getAffiliateUrl(asin: string): string {
  return `https://www.amazon.in/dp/${asin}?tag=${AFFILIATE_TAG}`;
}

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Smartphones', slug: 'smartphones', description: 'Flagships, midrange contenders, and battery endurance benchmarks.', productCount: 120 },
  { id: '2', name: 'Laptops', slug: 'laptops', description: 'Productivity ultrabooks, creator workstations, and gaming machines.', productCount: 85 },
  { id: '3', name: 'Audio', slug: 'audio', description: 'Over-ear ANC headphones, wireless earbuds, and studio monitors.', productCount: 64 },
  { id: '4', name: 'Cameras', slug: 'cameras', description: 'Mirrorless bodies, creator vlogging setups, and versatile primes.', productCount: 42 },
  { id: '5', name: 'Tablets', slug: 'tablets', description: 'Productivity slates, stylus-driven sketchpads, and media viewers.', productCount: 38 },
  { id: '6', name: 'Smartwatches', slug: 'smartwatches', description: 'Fitness trackers, GPS sport watches, and daily notification hubs.', productCount: 55 },
  { id: '7', name: 'Gaming', slug: 'gaming', description: 'Home consoles, handheld PCs, and low-latency peripherals.', productCount: 71 },
  { id: '8', name: 'TVs', slug: 'tvs', description: 'OLED reference panels, Mini-LED bright-room displays, and soundbars.', productCount: 29 },
];

export const ALL_PRODUCTS: Product[] = [
  {
    id: '1',
    asin: 'B0CHX2FQKJ',
    slug: 'apple-iphone-16-pro-max-review',
    title: 'Apple iPhone 16 Pro Max 256GB – Black Titanium',
    brand: 'Apple',
    category: 'Smartphones',
    price: 134900,
    originalPrice: 139900,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 2847,
    thumbnail: 'https://m.media-amazon.com/images/I/81JxBZJ8hML._SL1500_.jpg',
    images: [
      'https://m.media-amazon.com/images/I/81JxBZJ8hML._SL1500_.jpg',
      'https://m.media-amazon.com/images/I/61eDXs9JCNL._SL1500_.jpg',
      'https://m.media-amazon.com/images/I/71Mj7RVMJNL._SL1500_.jpg',
    ],
    description: 'Flagship iOS smartphone with 6.9-inch OLED display, A18 Pro silicon, titanium rails, and dedicated 5x telephoto optical zoom.',
    specs: {
      'Display': '6.9-inch Super Retina XDR OLED, 2868×1320, 120Hz ProMotion',
      'Chip': 'Apple A18 Pro (3nm fabrication)',
      'Rear Cameras': '48MP Main (f/1.78) + 48MP Ultra Wide (f/2.2) + 12MP 5x Telephoto (f/2.8)',
      'Front Camera': '12MP TrueDepth (f/1.9)',
      'Battery': '4685 mAh, tested 16h 40m continuous web browsing',
      'Storage': '256GB NVMe base',
      'Operating System': 'iOS 18',
      'Weight': '227 grams',
      'Water Resistance': 'IP68 (6 meters up to 30 minutes)',
    },
    features: [
      'A18 Pro silicon with sustained thermal dissipation improvements',
      '48MP Fusion sensor with 4K 120fps ProRes log recording',
      'Hardware camera capture switch with capacitive swipe zoom',
      'Grade 5 titanium chassis with matte textured glass back',
    ],
    affiliateUrl: getAffiliateUrl('B0CHX2FQKJ'),
    amazonUrl: 'https://www.amazon.in/dp/B0CHX2FQKJ',
    inStock: true,
    verdictScore: 9.1,
    verdictSummary: 'The iPhone 16 Pro Max sets the current benchmark for video capture fidelity and battery endurance in a flagship smartphone. However, the physical Camera Control key has a steep learning curve, and charging speeds still lag behind Android alternatives.',
    verdictPros: [
      'Class-leading video dynamic range and audio recording options',
      'Over 16 hours of real-world battery run time per charge cycle',
      'Consistent sustained performance without aggressive thermal throttling',
      'Titanium frame keeps weight manageable despite the larger 6.9-inch panel',
    ],
    verdictCons: [
      'High entry price with expensive official repair costs',
      '27W wired peak charging remains noticeably slower than rival devices',
      'Camera Control button placement feels awkward in one-handed portrait orientation',
    ],
    whoItIsFor: 'Content creators, mobile videographers, and power users deeply embedded in the Apple ecosystem who prioritize battery longevity and consistent color grading across lenses.',
    whoShouldSkip: 'Anyone currently holding an iPhone 15 Pro Max, budget-conscious buyers, or users who prioritize ultra-fast 65W+ wired recharge speeds.',
    isFeatured: true,
    isPublished: true,
    _dataSource: 'amazon-listing',
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-02-15T00:00:00Z',
  },
  {
    id: '2',
    asin: 'B0CMDWC436',
    slug: 'samsung-galaxy-s25-ultra-review',
    title: 'Samsung Galaxy S25 Ultra 256GB – Titanium Black',
    brand: 'Samsung',
    category: 'Smartphones',
    price: 129999,
    originalPrice: 134999,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 1923,
    thumbnail: 'https://m.media-amazon.com/images/I/71p-M3sPhhL._SL1500_.jpg',
    images: [
      'https://m.media-amazon.com/images/I/71p-M3sPhhL._SL1500_.jpg',
    ],
    description: 'Premium Android flagship featuring the Snapdragon 8 Elite platform, integrated S Pen stylus, and anti-reflective flat display.',
    specs: {
      'Display': '6.8-inch Dynamic AMOLED 2X, 3120×1440, 2600 nits peak, Anti-reflective glass',
      'Chip': 'Qualcomm Snapdragon 8 Elite for Galaxy',
      'Rear Cameras': '200MP Main + 50MP Ultra Wide + 50MP 5x Periscope + 10MP 3x Telephoto',
      'Front Camera': '12MP Dual Pixel (f/2.2)',
      'Battery': '5000 mAh with 45W wired charging',
      'Storage': '256GB UFS 4.0',
      'Operating System': 'One UI 7 on Android 15',
      'Weight': '219 grams',
      'Stylus': 'Embedded S Pen with Bluetooth LE',
    },
    features: [
      'Anti-reflective Gorilla Armor glass drastically minimizes glare in direct sunlight',
      'Quad-telephoto optical zoom matrix ranging from 0.6x to 100x digital zoom',
      'Integrated S Pen active stylus with low latency pressure sensitivity',
      '7 years of guaranteed OS upgrades and security patches',
    ],
    affiliateUrl: getAffiliateUrl('B0CMDWC436'),
    amazonUrl: 'https://www.amazon.in/dp/B0CMDWC436',
    inStock: true,
    verdictScore: 9.0,
    verdictSummary: 'The Galaxy S25 Ultra is the most versatile productivity handset available today. Its anti-reflective screen coating is genuinely useful, though low-light shutter lag on moving subjects remains an unresolved quirk.',
    verdictPros: [
      'Exceptional glare reduction makes outdoor readability unmatched',
      'S Pen integration provides unmatched precision for document annotation and signing',
      'Industry-leading 7-year software maintenance policy',
      'Strong sustained CPU/GPU throughput on the Snapdragon 8 Elite platform',
    ],
    verdictCons: [
      'Shutter response delay can result in blurry indoor shots of pets or moving children',
      'One UI interface carries significant pre-installed redundant software',
      'Box includes no charging adapter or protective case',
    ],
    whoItIsFor: 'Business professionals, digital sketchers, and mobile multitaskers who need stylus precision and the widest range of optical zoom focal lengths.',
    whoShouldSkip: 'Users wanting a pocket-friendly compact device or point-and-shoot photographers who frequently capture fast-moving indoor subjects.',
    isFeatured: true,
    isPublished: true,
    _dataSource: 'amazon-listing',
    createdAt: '2025-01-20T00:00:00Z',
    updatedAt: '2025-02-18T00:00:00Z',
  },
  {
    id: '3',
    asin: 'B09XS7JWHH',
    slug: 'sony-wh-1000xm5-review',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    brand: 'Sony',
    category: 'Audio',
    price: 26990,
    originalPrice: 34990,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 5621,
    thumbnail: 'https://m.media-amazon.com/images/I/61vVJMkphtL._SL1500_.jpg',
    images: [
      'https://m.media-amazon.com/images/I/61vVJMkphtL._SL1500_.jpg',
    ],
    description: 'Over-ear active noise cancelling headphones with dual processors, 8 microphones, LDAC codec support, and 30-hour battery life.',
    specs: {
      'Driver Unit': '30mm carbon fiber composite dome',
      'Frequency Response': '4Hz – 40,000Hz (JEITA active)',
      'Noise Cancelling': 'Auto NC Optimizer with 8 microphones & dual V1/QN1 chips',
      'Battery Life': 'Up to 30 hours (ANC on), 40 hours (ANC off)',
      'Bluetooth Version': '5.2 with LDAC, AAC, SBC codecs',
      'Weight': '250 grams',
      'Charging': 'USB-C (3 minutes quick charge gives 3 hours playback)',
    },
    features: [
      'Dual processor architecture dedicated to acoustic noise filtering',
      'Speak-to-Chat automatic ambient transparency upon detecting user voice',
      'Multipoint connection pairing two Bluetooth sources simultaneously',
      'Lightweight synthetic leather headband with stepless slider',
    ],
    affiliateUrl: getAffiliateUrl('B09XS7JWHH'),
    amazonUrl: 'https://www.amazon.in/dp/B09XS7JWHH',
    inStock: true,
    verdictScore: 9.3,
    verdictSummary: 'Sony WH-1000XM5 remains the gold standard for office and travel noise cancellation. The non-folding frame makes the carrying case bulky, but acoustic attenuation and voice call isolation are exceptional.',
    verdictPros: [
      'High-frequency background chatter and engine drone attenuation is top tier',
      'Comfortable 250g weight distribution for 6+ hour listening sessions',
      'Crystal-clear microphone beamforming during voice and video calls',
      'Fast 3-minute emergency charging yields hours of playback',
    ],
    verdictCons: [
      'Headband does not fold inward into a compact footprint like the predecessor XM4',
      'Synthetic leather earpads trap ear warmth in humid climates',
      'No official IP rating for water or sweat ingress',
    ],
    whoItIsFor: 'Frequent flyers, open-plan office workers, and students who need silence and multi-device Bluetooth switching.',
    whoShouldSkip: 'Gym-goers needing sweat-resistant workout audio, or travelers with minimal bag space who require a foldable headphone frame.',
    isFeatured: true,
    isPublished: true,
    _dataSource: 'amazon-listing',
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-02-12T00:00:00Z',
  },
  {
    id: '4',
    asin: 'B0CM5HZFNC',
    slug: 'macbook-pro-m4-review',
    title: 'Apple MacBook Pro 14" M4 Pro – Space Black',
    brand: 'Apple',
    category: 'Laptops',
    price: 198900,
    originalPrice: 199900,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 934,
    thumbnail: 'https://m.media-amazon.com/images/I/71an9eiBxpL._SL1500_.jpg',
    images: [
      'https://m.media-amazon.com/images/I/71an9eiBxpL._SL1500_.jpg',
    ],
    description: '14.2-inch professional notebook with Liquid Retina XDR display, M4 Pro silicon, Thunderbolt 5 ports, and up to 22 hours battery endurance.',
    specs: {
      'Display': '14.2-inch Liquid Retina XDR, 3024×1964, 1600 nits peak HDR, 120Hz',
      'Processor': 'Apple M4 Pro (12-core CPU, 16-core GPU, 16-core Neural Engine)',
      'Memory': '24GB unified memory (150GB/s bandwidth)',
      'Storage': '512GB PCIe NVMe SSD',
      'Ports': '3× Thunderbolt 5 (USB-C), HDMI 2.1, SDXC card slot, MagSafe 3',
      'Battery': '72.4 Wh lithium-polymer, up to 22 hours video playback',
      'Weight': '1.60 kg',
      'Audio': 'Six-speaker sound system with force-cancelling woofers',
    },
    features: [
      'M4 Pro architectural gains deliver desktop-grade compilation speeds on battery power',
      'Thunderbolt 5 bandwidth supports up to 120 Gbps external transfer rates',
      'Nano-texture display option cuts ambient reflections in harsh studio lighting',
      'Class-leading trackpad, keyboard, and speaker acoustic fidelity',
    ],
    affiliateUrl: getAffiliateUrl('B0CM5HZFNC'),
    amazonUrl: 'https://www.amazon.in/dp/B0CM5HZFNC',
    inStock: true,
    verdictScore: 9.5,
    verdictSummary: 'The 14-inch MacBook Pro M4 Pro offers unmatched efficiency: it performs identically on wall power and on battery, runs almost silent under typical loads, and lasts over 18 hours in real-world office tasks.',
    verdictPros: [
      'Unthrottled sustained compute performance whether plugged in or operating on battery',
      'Liquid Retina XDR panel offers genuine reference-grade contrast and 1000 nits SDR brightness',
      'Excellent port selection with full-size SDXC card reader and HDMI 2.1',
      'Class-leading keyboard tactility, precision trackpad, and six-speaker acoustics',
    ],
    verdictCons: [
      'Steep memory and storage upgrade pricing tiers at purchase time',
      'Zero post-purchase hardware component upgradability',
      'Display notch cuts slightly into the macOS menu bar area',
    ],
    whoItIsFor: 'Software engineers, photo editors, video producers, and data analysts who require workstation power without tethering to an electrical outlet.',
    whoShouldSkip: 'Casual web surfers who would be better served by the lighter and cheaper MacBook Air, or dedicated PC gamers dependent on DirectX 12 titles.',
    isFeatured: true,
    isPublished: true,
    _dataSource: 'amazon-listing',
    createdAt: '2025-01-25T00:00:00Z',
    updatedAt: '2025-02-20T00:00:00Z',
  },
  {
    id: '5',
    asin: 'B0D3J6L2ZL',
    slug: 'google-pixel-9-pro-review',
    title: 'Google Pixel 9 Pro 256GB – Obsidian',
    brand: 'Google',
    category: 'Smartphones',
    price: 109999,
    originalPrice: 114999,
    currency: 'INR',
    rating: 4.5,
    reviewCount: 1124,
    thumbnail: 'https://m.media-amazon.com/images/I/71a4MI0TVNL._SL1500_.jpg',
    images: [
      'https://m.media-amazon.com/images/I/71a4MI0TVNL._SL1500_.jpg',
    ],
    description: 'Compact 6.3-inch flagship phone with Super Actua OLED display, Tensor G4 processor, vapor chamber cooling, and 7 years of Pixel drops.',
    specs: {
      'Display': '6.3-inch Super Actua LTPO OLED, 1280×2856, 1-120Hz, 3000 nits peak',
      'Chip': 'Google Tensor G4 with Titan M2 security coprocessor',
      'RAM': '16GB LPDDR5X',
      'Rear Cameras': '50MP Main (f/1.68) + 48MP Ultra Wide with Macro + 48MP 5x Telephoto',
      'Front Camera': '42MP Dual PD with autofocus',
      'Battery': '4700 mAh with 27W wired fast charging',
      'Operating System': 'Android 15 with 7-year software guarantee',
      'Weight': '199 grams',
    },
    features: [
      'Compact 6.3-inch form factor maintaining full pro-tier camera hardware',
      'Dedicated vapor chamber cooling plate for improved sustained thermals',
      'Ultrasonic in-display fingerprint sensor replaces optical scanner',
      'Super Actua 3000 nits display offering top-tier outdoor visibility',
    ],
    affiliateUrl: getAffiliateUrl('B0D3J6L2ZL'),
    amazonUrl: 'https://www.amazon.in/dp/B0D3J6L2ZL',
    inStock: true,
    verdictScore: 8.8,
    verdictSummary: 'Google Pixel 9 Pro finally delivers full flagship camera specifications in a manageable 6.3-inch chassis with premium matte glass. Raw gaming GPU horsepower still trails Snapdragon 8 Elite, but still photography remains unmatched.',
    verdictPros: [
      'Uncompromised triple-camera telephoto system in a pocket-friendly 6.3-inch body',
      'Natural skin tone rendering and reliable point-and-shoot dynamic range',
      'Responsive ultrasonic biometric scanner and clean Android software stack',
      'Matte glass finish resists oily fingerprints effectively',
    ],
    verdictCons: [
      'Tensor G4 synthetic benchmark scores trail comparable Snapdragon flagships',
      '27W charging speed requires over 80 minutes for a 0 to 100% full charge',
      'Pixel AI cloud features require periodic internet connectivity to process',
    ],
    whoItIsFor: 'Photographers and enthusiasts who prefer a comfortable one-handed form factor without sacrificing telephoto zoom range or display quality.',
    whoShouldSkip: 'Hardcore mobile gamers wanting maximum frame rates in demanding 3D titles, or users needing sub-30 minute charging cycles.',
    isFeatured: false,
    isPublished: true,
    _dataSource: 'amazon-listing',
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-02-22T00:00:00Z',
  },
  {
    id: '6',
    asin: 'B0BDGXZS1Z',
    slug: 'ipad-pro-m4-review',
    title: 'Apple iPad Pro M4 11-inch WiFi 256GB – Space Black',
    brand: 'Apple',
    category: 'Tablets',
    price: 99900,
    originalPrice: 104900,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 762,
    thumbnail: 'https://m.media-amazon.com/images/I/71SjXBRUBNL._SL1500_.jpg',
    images: [
      'https://m.media-amazon.com/images/I/71SjXBRUBNL._SL1500_.jpg',
    ],
    description: 'Ultra-thin 5.3mm tablet featuring Tandem OLED Ultra Retina XDR display, M4 silicon, and Apple Pencil Pro haptic squeeze support.',
    specs: {
      'Display': '11-inch Tandem OLED Ultra Retina XDR, 2420×1668, 1600 nits peak HDR',
      'Processor': 'Apple M4 chip (9-core CPU, 10-core GPU, 16-core NPU)',
      'Storage': '256GB base configuration',
      'Thickness': '5.3 mm profile',
      'Cameras': '12MP Wide rear camera with LiDAR scanner + Landscape 12MP TrueDepth front',
      'Audio': 'Four-speaker audio array with studio-quality microphones',
      'Weight': '444 grams',
      'Connectivity': 'Wi-Fi 6E, Bluetooth 5.3, Thunderbolt / USB 4 port',
    },
    features: [
      'Tandem OLED panel stacks two OLED layers for 1000 nits full-screen SDR brightness',
      '5.3mm rigid chassis makes it the thinnest device Apple has ever manufactured',
      'Landscape-oriented TrueDepth camera fixes awkward off-center video call framing',
      'Apple Pencil Pro support with barrel roll gyroscope and haptic feedback',
    ],
    affiliateUrl: getAffiliateUrl('B0BDGXZS1Z'),
    amazonUrl: 'https://www.amazon.in/dp/B0BDGXZS1Z',
    inStock: true,
    verdictScore: 9.0,
    verdictSummary: 'The iPad Pro M4 boasts the finest portable display hardware on the market inside an impossibly thin 5.3mm frame. It is held back strictly by iPadOS workflow constraints rather than hardware limitations.',
    verdictPros: [
      'Tandem OLED delivers true black levels with zero bloom around HDR highlights',
      'Remarkably thin 5.3mm aluminum chassis is balanced and easy to hold',
      'Landscape front camera position greatly improves video conference ergonomics',
      'M4 processor handles 4K timeline scrubbing and high-layer illustration files instantly',
    ],
    verdictCons: [
      'iPadOS window management still imposes barriers compared to macOS desktop workflows',
      'Pencil Pro and Magic Keyboard must be bought separately at significant extra expense',
      'Base 256GB tier cannot be expanded via external microSD storage',
    ],
    whoItIsFor: 'Digital illustrators, visual artists, and mobile professionals seeking an unrivaled OLED canvas and stylus experience.',
    whoShouldSkip: 'Users looking for a traditional desktop replacement or software engineers needing full terminal background daemon workflows.',
    isFeatured: false,
    isPublished: true,
    _dataSource: 'amazon-listing',
    createdAt: '2025-02-05T00:00:00Z',
    updatedAt: '2025-02-25T00:00:00Z',
  },
];

export const ALL_VIDEOS: Video[] = [
  {
    id: '1',
    youtubeId: 'dQw4w9WgXcQ',
    title: 'iPhone 16 Pro Max Review: 4 Months of Camera and Battery Benchmarking',
    channelName: 'Gadget Verse',
    channelId: 'gadget-verse',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    publishedAt: '2025-02-01T00:00:00Z',
    viewCount: 245000,
    duration: '18:32',
    tags: ['iPhone 16 Pro Max', 'Apple', 'Smartphone Review'],
    isPublished: true,
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: '2',
    youtubeId: 'oHg5SJYRHA0',
    title: 'Samsung Galaxy S25 Ultra vs iPhone 16 Pro Max: Optical Zoom and Glare Tests',
    channelName: 'Tech Space',
    channelId: 'tech-space',
    thumbnail: 'https://img.youtube.com/vi/oHg5SJYRHA0/maxresdefault.jpg',
    publishedAt: '2025-01-28T00:00:00Z',
    viewCount: 189000,
    duration: '22:14',
    tags: ['Galaxy S25 Ultra', 'iPhone 16 Pro Max', 'Camera Comparison'],
    isPublished: true,
    createdAt: '2025-01-28T00:00:00Z',
  },
  {
    id: '3',
    youtubeId: 'y6120QOlsfU',
    title: 'Sony WH-1000XM5 Lab Test: ANC Isolation and Mic Quality Under Loud Noise',
    channelName: 'Gadget Bits',
    channelId: 'gadget-bits',
    thumbnail: 'https://img.youtube.com/vi/y6120QOlsfU/maxresdefault.jpg',
    publishedAt: '2025-01-25T00:00:00Z',
    viewCount: 98000,
    duration: '14:45',
    tags: ['Sony XM5', 'Noise Cancelling', 'Audio Review'],
    isPublished: true,
    createdAt: '2025-01-25T00:00:00Z',
  },
  {
    id: '4',
    youtubeId: 'rokGy0huYEA',
    title: 'MacBook Pro 14 M4 Pro: Logic Pro and 8K Video Export Benchmarks',
    channelName: 'Gadget Adda',
    channelId: 'gadget-adda',
    thumbnail: 'https://img.youtube.com/vi/rokGy0huYEA/maxresdefault.jpg',
    publishedAt: '2025-01-22T00:00:00Z',
    viewCount: 134000,
    duration: '19:08',
    tags: ['MacBook Pro M4', 'Apple Silicon', 'Laptop Review'],
    isPublished: true,
    createdAt: '2025-01-22T00:00:00Z',
  },
  {
    id: '5',
    youtubeId: '6_b6zVHhBt4',
    title: 'Midrange Smartphone Shootout: Battery Endurance and Thermal Throttle Test',
    channelName: 'Tech Buddie',
    channelId: 'tech-buddie',
    thumbnail: 'https://img.youtube.com/vi/6_b6zVHhBt4/maxresdefault.jpg',
    publishedAt: '2025-01-18T00:00:00Z',
    viewCount: 67000,
    duration: '12:30',
    tags: ['Smartphone Guide', 'Budget Tech', 'Battery Test'],
    isPublished: true,
    createdAt: '2025-01-18T00:00:00Z',
  },
  {
    id: '6',
    youtubeId: 'hY7m5jjJ9mM',
    title: 'Google Pixel 9 Pro Real World Camera & Sensor Teardown',
    channelName: 'Tech States',
    channelId: 'tech-states',
    thumbnail: 'https://img.youtube.com/vi/hY7m5jjJ9mM/maxresdefault.jpg',
    publishedAt: '2025-01-15T00:00:00Z',
    viewCount: 52000,
    duration: '16:20',
    tags: ['Pixel 9 Pro', 'Google', 'Photography'],
    isPublished: true,
    createdAt: '2025-01-15T00:00:00Z',
  },
];

export const MOCK_REVIEWS: Record<string, Review[]> = {
  'apple-iphone-16-pro-max-review': [
    {
      id: 'r1',
      productId: '1',
      source: 'AMAZON',
      authorName: 'Rohan Sharma',
      authorLocation: 'Verified Amazon Purchase',
      rating: 5,
      title: 'Battery life easily lasts two days of moderate office work',
      body: 'Upgraded from an iPhone 13 Pro. The 5x telephoto camera is crisp in outdoor daylight, and the 4K 120fps recording is smooth for recording clips of my kids. The battery comfortably lasts through 1.5 to 2 days between recharges.',
      isVerified: true,
      sentimentScore: 0.9,
      sourceDate: '2025-02-10T00:00:00Z',
      createdAt: '2025-02-10T00:00:00Z',
      isHelpful: 142,
    },
    {
      id: 'r2',
      productId: '1',
      source: 'REDDIT',
      authorName: 'u/LensAnalyst',
      authorLocation: 'r/gadgets',
      rating: 4,
      title: 'Camera control key requires adjustment, but audio mixing is stellar',
      body: 'The capacitive camera control switch is too stiff for quick one-handed snaps in portrait mode. However, the Audio Mix studio vocal isolation feature during video capture works remarkably well when recording in windy environments.',
      isVerified: false,
      sentimentScore: 0.6,
      sourceDate: '2025-01-28T00:00:00Z',
      createdAt: '2025-01-28T00:00:00Z',
      isHelpful: 89,
    },
    {
      id: 'r3',
      productId: '1',
      source: 'EXPERT',
      authorName: 'GadgetLens Lab Team',
      rating: 5,
      title: 'Editorial Benchmarking Verdict: 9.1 / 10',
      body: 'In our standardized battery discharge test, the 16 Pro Max achieved 16 hours and 40 minutes of continuous automated web browsing at 150 nits brightness. Display color accuracy registered an average Delta-E of 1.1 across the DCI-P3 spectrum.',
      isVerified: true,
      sentimentScore: 0.92,
      sourceDate: '2025-01-15T00:00:00Z',
      createdAt: '2025-01-15T00:00:00Z',
      isHelpful: 310,
    },
  ],
};
